# Generated by Django 5.2 on 2025-04-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAppel', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('etatAppel', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('relationEmploye', models.CharField(choices=[('CONJOINT', 'Conjoint(e)'), ('ENFANT', 'Enfant'), ('PARENT', 'Parent'), ('AUTRE', 'Autre')], max_length=20)),
                ('dateNaissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCompagnie', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('emailCompagnie', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ConseillerRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('conseillerRH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriels', to='api.conseillerrh')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeNotification', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('SYSTEME', 'Notification système')], max_length=20)),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('RECUE', 'Reçue'), ('ECHEC', 'Échec')], default='ENVOYEE', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='appel',
            name='conseillerRH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='api.conseillerrh'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to='api.employe'),
        ),
        migrations.AddField(
            model_name='appel',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='api.employe'),
        ),
        migrations.AddField(
            model_name='notification',
            name='appel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.appel'),
        ),
        migrations.AddField(
            model_name='notification',
            name='compagnieAssurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.compagnieassurance'),
        ),
    ]
